name: app
type: golang:1.12
disk: 128

hooks:
  build: |
    set -eux
    # fail to build if gen writes a file
    go run ./cmd/gen --exit-code --output ./pkg/platformsh/enums_gen.go enums ./data/enums.yaml
    go run ./cmd/gen --exit-code --output ./pkg/platformsh/environment_gen.go variables ./data/variables.yaml
    go build -v -a -ldflags '-s -w -extldflags "-static"' .

web:
  commands:
    start: ./super-potato

  upstream:
    socket_family: unix
    protocol: http

  locations:
    /:
      passthru: true
      allow: false

relationships:
  cache: memcache:memcached
  database: database:mysql
  queue: rabbitqueue:rabbitmq
