name: app
type: golang:1.12
disk: 128

hooks:
  build: !include
    type: string
    path: .platform/build.sh

mounts:
  /var/tmp:
    source: tmp
    source_path: tmp
  /var/log:
    source: local
    source_path: log
  /var/pki:
    source: service
    service: storage
    source_path: pki

web:
  commands:
    start: ./super-potato serve

  upstream:
    socket_family: unix
    protocol: http

  locations:
    /:
      passthru: true
      allow: false

relationships:
  sessions: redis-sessions:redis
