name: app
type: golang:1.12
disk: 128

hooks:
  build: |
    set -eux
    go build -v -a -ldflags '-s -w -extldflags "-static"' .

web:
  commands:
    start: ./super-potato

  upstream:
    socket_family: unix
    protocol: http

  locations:
    /:
      passthru: true
      allow: false
