name: app
type: golang:1.12
disk: 128

hooks:
  build: !include
    type: string
    path: .platform/build.sh
  deploy: !include
    type: string
    path: .platform/deploy.sh
  post_deploy: !include
    type: string
    path: .platform/post_deploy.sh

mounts:
  tmp:
    source: tmp
    source_path: tmp
  pki:
    source: service
    service: storage
    source_path: pki

web:
  commands:
    start: ./super-potato serve

  upstream:
    socket_family: unix
    protocol: http

  locations:
    /:
      passthru: true
      allow: false
