name: app
type: golang:1.12
disk: 1024

hooks:
  build: |
    set -eux
    time go mod vendor
    time go run ./gen --exit-code
    time go build -v -a -ldflags '-s -w' .
    ls -l super-potato
  deploy: |
    time ./super-potato deploy

variables:
  env:
    PKI_ROOT_CERTIFICATE: !include
      type: string
      path: .platform/root.pem
    PKI_INTERMEDIATE_CERTIFICATE: !include
      type: string
      path: .platform/intermediate.pem

mounts:
  /var/tmp:
    source: tmp
    source_path: tmp
  /var/log:
    source: local
    source_path: log
  /var/pki:
    source: local
    source_path: pki

web:
  commands:
    start: ./super-potato serve

  upstream:
    socket_family: unix
    protocol: http

  locations:
    /:
      passthru: true
      allow: false

relationships:
  sessions: mongo-sessions:mongodb
  database: pg-database:postgresql
