name: app
type: golang:1.12
disk: 128

hooks:
  build: |
    set -eux
    # fail to build if gen writes a file
    go run ./pkg/platformsh/internal/cmd/gen -exit-code -enum ./pkg/platformsh/enums_gen.go
    go build -v -a -ldflags '-s -w -extldflags "-static"' .

web:
  commands:
    start: ./super-potato

  upstream:
    socket_family: unix
    protocol: http

  locations:
    /:
      passthru: true
      allow: false

relationships:
  cache: memcache:memcached
  database: database:mysql
  queue: rabbitqueue:rabbitmq
