name: app
type: golang:1.12
disk: 128

hooks:
  build: |
    set -eux
    time go get ./...
    time go build -a -ldflags '-s -w -extldflags "-static"' ./cmd/gen
    # fail to build if gen writes a file
    time ./gen --exit-code --output ./pkg/platformsh/enums_gen.go enums ./data/enums.yaml
    time ./gen --exit-code --output ./pkg/platformsh/environment_gen.go variables ./data/variables.yaml
    time ./gen --exit-code --output ./cmd/server/generated.go api ./data/variables.yaml
    time go build -a -ldflags '-s -w -extldflags "-static"' .
    ls -l gen super-potato

web:
  commands:
    start: ./super-potato

  upstream:
    socket_family: unix
    protocol: http

  locations:
    /:
      passthru: true
      allow: false

relationships:
  cache: memcache:memcached
  database: database:mysql
  queue: rabbitqueue:rabbitmq
