checks:
  go: true

build:
  environment:
    go:
      version: go1.12.5
    variables:
      GO111MODULE: on

  nodes:
    analysis:
      project_setup:
        override:
          - "true"
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run
    tests: {}

filter:
  excluded_paths:
    - "vendor/*"
