https://{default}/:
  type: upstream
  upstream: app:http

https://{default}/api/:
  type: upstream
  upstream: app:http
  cache:
    enabled: false

http://{default}/:
  type: redirect
  to: https://{default}/
