https://{default}/:
  type: upstream
  upstream: app:http

https://api.{default}/:
  type: upstream
  upstream: app:http
  cache:
    enabled: false
  tls:
    client_authentication: require
    client_certificate_authorities:
      - !include
        type: string
        path: root.pem
      - !include
        type: string
        path: intermediate.pem

http://{default}/:
  type: redirect
  to: https://{default}/
